### PR TITLE
added a marker to improve visibility of last position

### PR DESCRIPTION
**Pull request by kartenkarsten**
the marker can be draged to update the position

### CODE REVIEW

**Comment by zimmicz** [comment]
@kartenkarsten I'm not sure I like the idea. Is it necessary to hide the marker and the control on every even click?

**Comment by kartenkarsten** [comment]
It's not necessary - but I prefer to have a possibility to hide it again. Maybe we should add a close button inside the control to collapse it.

**Comment by zimmicz** [comment]
@kartenkarsten this seems to be a bit overhead for such a simple control. I guess a fork would be appropriate way of implementing this.

**Comment by kartenkarsten** [comment]
@zimmicz you are right this would result in a more complex control - I'll go on develloping it on my branch

**Comment by zimmicz** [comment]
@kartenkarsten that's great to hear, I'm looking forward to seeing the
result ;)

On Tue, Feb 17, 2015 at 9:56 PM, Karsten Hinz notifications@github.com
wrote:

> @zimmicz https://github.com/zimmicz you are right this would result in
> a more complex control - I'll go on develloping it on my branch
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/zimmicz/Leaflet-Coordinates-Control/pull/2#issuecomment-74751452
> .

## 

Michal Zimmermann (zimmi)
WWW: http://www.zimmi.cz

**Pull request closed without merging**
